async function blosc_codec(moduleArg={}){var moduleRtn;var f=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,n=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;if(n){const {createRequire:a}=await import("node:module");var require=a(import.meta.url)}var t="./this.program",u=(a,b)=>{throw b;},x=import.meta.url,y="",A,C;
if(n){var fs=require("node:fs");x.startsWith("file:")&&(y=require("node:path").dirname(require("node:url").fileURLToPath(x))+"/");C=a=>{a=D(a)?new URL(a):a;return fs.readFileSync(a)};A=async a=>{a=D(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(t=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);u=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{y=(new URL(".",x)).href}catch{}ba&&(C=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";
b.send(null);return new Uint8Array(b.response)});A=async a=>{if(D(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}
var ca=console.log.bind(console),E=console.error.bind(console),F,G=!1,H,D=a=>a.startsWith("file://"),da,ea,fa,I,K,L,M,N,ha,ia,ja,ka,ma=!1;function na(){var a=O.buffer;fa=new Int8Array(a);K=new Int16Array(a);I=new Uint8Array(a);L=new Uint16Array(a);M=new Int32Array(a);N=new Uint32Array(a);ha=new Float32Array(a);ia=new Float64Array(a);ja=new BigInt64Array(a);ka=new BigUint64Array(a)}
function oa(a){f.onAbort?.(a);a="Aborted("+a+")";E(a);G=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ea?.(a);throw a;}var pa;async function qa(a){if(!F)try{var b=await A(a);return new Uint8Array(b)}catch{}if(a==pa&&F)a=new Uint8Array(F);else if(C)a=C(a);else throw"both async and sync fetching of the wasm failed";return a}
async function ra(a,b){try{var c=await qa(a);return await WebAssembly.instantiate(c,b)}catch(d){E(`failed to asynchronously prepare wasm: ${d}`),oa(d)}}async function sa(a){var b=pa;if(!F&&!D(b)&&!n)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){E(`wasm streaming compile failed: ${d}`),E("falling back to ArrayBuffer instantiation")}return ra(b,a)}
class ta{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var ua=a=>{for(;0<a.length;)a.shift()(f)},va=[],wa=[],xa=()=>{var a=f.preRun.shift();wa.push(a)},P=!0;class ya{constructor(a){this.K=a-24}}var za=0,Aa=0,Q=a=>{for(var b="";;){var c=I[a++];if(!c)return b;b+=String.fromCharCode(c)}},R={},S={},T={},U=class extends Error{constructor(a){super(a);this.name="BindingError"}},Ba=a=>{throw new U(a);};
function Ca(a,b,c={}){var d=b.name;if(!a)throw new U(`type "${d}" must have a positive integer typeid pointer`);if(S.hasOwnProperty(a)){if(c.N)return;throw new U(`Cannot register type '${d}' twice`);}S[a]=b;delete T[a];R.hasOwnProperty(a)&&(b=R[a],delete R[a],b.forEach(e=>e()))}function V(a,b,c={}){return Ca(a,b,c)}
var Da=(a,b,c)=>{switch(b){case 1:return c?d=>fa[d]:d=>I[d];case 2:return c?d=>K[d>>1]:d=>L[d>>1];case 4:return c?d=>M[d>>2]:d=>N[d>>2];case 8:return c?d=>ja[d>>3]:d=>ka[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ea=[],W=[0,1,,1,null,1,!0,1,!1,1],Fa=a=>{9<a&&0===--W[a+1]&&(W[a]=void 0,Ea.push(a))},Ga=a=>{if(!a)throw new U(`Cannot use deleted val. handle = ${a}`);return W[a]},Ha=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;
default:const b=Ea.pop()||W.length;W[b]=a;W[b+1]=1;return b}};function Ia(a){return this.F(N[a>>2])}var Ja={name:"emscripten::val",F:a=>{var b=Ga(a);Fa(a);return b},I:(a,b)=>Ha(b),J:Ia,H:null},Ka=(a,b)=>{switch(b){case 4:return function(c){return this.F(ha[c>>2])};case 8:return function(c){return this.F(ia[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},La=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Ma(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].H)return!0;return!1}
var Na=(a,b)=>{if(void 0===f[a].G){var c=f[a];f[a]=function(...d){if(!f[a].G.hasOwnProperty(d.length))throw new U(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${f[a].G})!`);return f[a].G[d.length].apply(this,d)};f[a].G=[];f[a].G[c.L]=c}},Oa=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].G&&void 0!==f[a].G[c])throw new U(`Cannot register public name '${a}' twice`);Na(a,a);if(f[a].G.hasOwnProperty(c))throw new U(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
f[a].G[c]=b}else f[a]=b,f[a].L=c},Pa=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(N[b+4*d>>2]);return c},Qa=class extends Error{constructor(a){super(a);this.name="InternalError"}},Sa=(a,b)=>{a=Q(a);var c=Ra.get(b);if("function"!=typeof c)throw new U(`unknown function pointer with signature ${a}: ${b}`);return c};class Ta extends Error{}
var Ya=a=>{a=Xa(a);var b=Q(a);X(a);return b},Za=(a,b)=>{function c(g){e[g]||S[g]||(T[g]?T[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new Ta(`${a}: `+d.map(Ya).join([", "]));},$a=(a,b)=>{function c(k){k=b(k);if(k.length!==d.length)throw new Qa("Mismatched type converter count");for(var l=0;l<d.length;++l)V(d[l],k[l])}var d=[];d.forEach(k=>T[k]=a);var e=Array(a.length),g=[],h=0;for(let [k,l]of a.entries())S.hasOwnProperty(l)?e[k]=S[l]:(g.push(l),R.hasOwnProperty(l)||(R[l]=[]),
R[l].push(()=>{e[k]=S[l];++h;h===g.length&&c(e)}));0===g.length&&c(e)},ab=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},bb=(a,b,c)=>{var d=I;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|
h>>6&63;d[b++]=128|h&63;g++}}d[b]=0;return b-e},cb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},db=globalThis.TextDecoder&&new TextDecoder,eb=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},fb=(a,b=0,c,d)=>{c=eb(a,b,c,d);if(16<c-b&&a.buffer&&db)return db.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&
63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},gb=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,hb=(a,b,c)=>{a>>=1;b=eb(L,a,b/2,c);if(16<b-a&&gb)return gb.decode(L.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(L[a]);return c},ib=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<
c;++e)K[b>>1]=a.charCodeAt(e),b+=2;K[b>>1]=0;return b-d},jb=a=>2*a.length,kb=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var g=N[a+e];if(!g&&!c)break;d+=String.fromCodePoint(g)}return d},lb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.codePointAt(e);65535<g&&e++;M[b>>2]=g;b+=4;if(b+4>c)break}M[b>>2]=0;return b-d},mb=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},nb=0,ob=[],pb=a=>{var b=ob.length;ob.push(a);return b},
qb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,g=N[b+4*d>>2],h=S[g];if(void 0===h)throw a=`${`parameter ${d}`} has unknown type ${Ya(g)}`,new U(a);c[e]=h}return c},rb=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(N[b>>2]=Ha(d));return a},sb={},tb=a=>{var b=sb[a];return void 0===b?Q(a):b},Y={},ub=a=>{H=a;P||0<nb||(f.onExit?.(a),G=!0);u(a,new ta(a))},vb=a=>{if(!G)try{a()}catch(b){b instanceof ta||"unwind"==b||u(1,b)}finally{if(!(P||0<nb))try{H=a=H,ub(a)}catch(b){b instanceof ta||"unwind"==b||u(1,b)}}},
wb={},yb=()=>{if(!xb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:t||"./this.program"},b;for(b in wb)void 0===wb[b]?delete a[b]:a[b]=wb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);xb=c}return xb},xb,zb=[null,[],[]];f.noExitRuntime&&(P=f.noExitRuntime);f.print&&(ca=f.print);f.printErr&&(E=f.printErr);f.wasmBinary&&(F=f.wasmBinary);f.thisProgram&&(t=f.thisProgram);
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();
var Ab,X,Xa,Bb,O,Ra,Cb={x:(a,b,c)=>{var d=new ya(a);N[d.K+16>>2]=0;N[d.K+4>>2]=b;N[d.K+8>>2]=c;za=a;Aa++;throw za;},p:()=>oa(""),f:(a,b,c,d,e)=>{b=Q(b);d=0n===d;let g=h=>h;if(d){const h=8*c;g=k=>BigInt.asUintN(h,k);e=g(e)}V(a,{name:b,F:g,I:(h,k)=>{"number"==typeof k&&(k=BigInt(k));return k},J:Da(b,c,!d),H:null})},i:(a,b,c,d)=>{b=Q(b);V(a,{name:b,F:function(e){return!!e},I:function(e,g){return g?c:d},J:function(e){return this.F(I[e])},H:null})},g:a=>V(a,Ja),e:(a,b,c)=>{b=Q(b);V(a,{name:b,F:d=>d,I:(d,
e)=>e,J:Ka(b,c),H:null})},d:(a,b,c,d,e,g,h)=>{var k=Pa(b,c);a=Q(a);a=ab(a);e=Sa(d,e);Oa(a,function(){Za(`Cannot call ${a} due to unbound types`,k)},b-1);$a(k,l=>{var m=[l[0],null].concat(l.slice(1));l=a;var v=a;var z=e,p=m.length;if(2>p)throw new U("argTypes array size mismatch! Must at least get return value and 'this' types!");var B=null!==m[1]&&!1,J=Ma(m),Ua=!m[0].M,q=m[0],w=m[1];z=[v,Ba,z,g,La,q.F.bind(q),w?.I.bind(w)];for(q=2;q<p;++q)w=m[q],z.push(w.I.bind(w));if(!J)for(q=B?1:2;q<m.length;++q)null!==
m[q].H&&z.push(m[q].H);J=Ma(m);q=m.length-2;var r=[];w=["fn"];B&&w.push("thisWired");for(p=0;p<q;++p)r.push(`arg${p}`),w.push(`arg${p}Wired`);r=r.join(",");w=w.join(",");r=`return function (${r}) {\n`;J&&(r+="var destructors = [];\n");var Va=J?"destructors":"null",la="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");B&&(r+=`var thisWired = toClassParamWire(${Va}, this);\n`);for(p=0;p<q;++p){var Wa=`toArg${p}Wire`;r+=`var arg${p}Wired = ${Wa}(${Va}, arg${p});\n`;
la.push(Wa)}r+=(Ua||h?"var rv = ":"")+`invoker(${w});\n`;if(J)r+="runDestructors(destructors);\n";else for(p=B?1:2;p<m.length;++p)B=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==m[p].H&&(r+=`${B}_dtor(${B});\n`,la.push(`${B}_dtor`));Ua&&(r+="var ret = fromRetWire(rv);\nreturn ret;\n");m=(new Function(la,r+"}\n"))(...z);v=Object.defineProperty(m,"name",{value:v});m=b-1;if(!f.hasOwnProperty(l))throw new Qa("Replacing nonexistent public symbol");void 0!==f[l].G&&void 0!==m?f[l].G[m]=v:(f[l]=v,f[l].L=
m);return[]})},b:(a,b,c,d,e)=>{b=Q(b);let g=k=>k;if(0===d){var h=32-8*c;g=k=>k<<h>>>h;e=g(e)}V(a,{name:b,F:g,I:(k,l)=>l,J:Da(b,c,0!==d),H:null})},a:(a,b,c)=>{function d(g){return new e(fa.buffer,N[g+4>>2],N[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=Q(c);V(a,{name:c,F:d,J:d},{N:!0})},h:(a,b)=>{b=Q(b);V(a,{name:b,F(c){var d=(d=c+4)?fb(I,d,N[c>>2],!0):"";X(c);return d},I(c,d){d instanceof ArrayBuffer&&
(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new U("Cannot pass non-string to std::string");var g=e?cb(d):d.length;var h=Ab(4+g+1),k=h+4;N[h>>2]=g;e?bb(d,k,g+1):I.set(d,k);null!==c&&c.push(X,h);return h},J:Ia,H(c){X(c)}})},c:(a,b,c)=>{c=Q(c);if(2===b){var d=hb;var e=ib;var g=jb}else d=kb,e=lb,g=mb;V(a,{name:c,F:h=>{var k=d(h+4,N[h>>2]*b,!0);X(h);return k},I:(h,k)=>{if("string"!=typeof k)throw new U(`Cannot pass non-string to C++ string type ${c}`);
var l=g(k),m=Ab(4+l+b);N[m>>2]=l/b;e(k,m+4,l+b);null!==h&&h.push(X,m);return m},J:Ia,H(h){X(h)}})},j:(a,b)=>{b=Q(b);V(a,{M:!0,name:b,F:()=>{},I:()=>{}})},n:()=>{P=!1;nb=0},q:(a,b,c)=>{var [d,...e]=qb(a,b);b=d.I.bind(d);var g=e.map(l=>l.J.bind(l));a--;var h={toValue:Ga};a=g.map((l,m)=>{var v=`argFromPtr${m}`;h[v]=l;return`${v}(args${m?"+"+8*m:""})`});switch(c){case 0:var k="toValue(handle)";break;case 2:k="new (toValue(handle))";break;case 3:k="";break;case 1:h.getStringOrSymbol=tb,k="toValue(handle)[getStringOrSymbol(methodName)]"}k+=
`(${a})`;d.M||(h.toReturnWire=b,h.emval_returnValue=rb,k=`return emval_returnValue(toReturnWire, destructorsRef, ${k})`);k=`return function (handle, methodName, destructorsRef, args) {\n${k}\n}`;c=(new Function(Object.keys(h),k))(...Object.values(h));k=`methodCaller<(${e.map(l=>l.name)}) => ${d.name}>`;return pb(Object.defineProperty(c,"name",{value:k}))},l:(a,b,c,d,e)=>ob[a](b,c,d,e),k:a=>{var b=Ga(a);La(b);Fa(a)},o:(a,b)=>{Y[a]&&(clearTimeout(Y[a].id),delete Y[a]);if(!b)return 0;var c=setTimeout(()=>
{delete Y[a];vb(()=>Bb(a,performance.now()))},b);Y[a]={id:c,O:b};return 0},r:a=>{var b=I.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-O.buffer.byteLength+65535)/65536|0;try{O.grow(d);na();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},v:(a,b)=>{var c=0,d=0,e;for(e of yb()){var g=b+c;N[a+d>>2]=g;c+=bb(e,g,Infinity)+1;d+=4}return 0},w:(a,b)=>{var c=yb();N[a>>2]=c.length;
a=0;for(var d of c)a+=cb(d)+1;N[b>>2]=a;return 0},u:()=>52,s:function(){return 70},t:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var h=N[b>>2],k=N[b+4>>2];b+=8;for(var l=0;l<k;l++){var m=a,v=I[h+l],z=zb[m];0===v||10===v?((1===m?ca:E)(fb(z)),z.length=0):z.push(v)}e+=k}N[d>>2]=e;return 0},m:ub},Z;
Z=await (async function(){function a(c){c=Z=c.exports;Ab=c.A;X=c.B;Xa=c.C;Bb=c.E;O=c.y;Ra=c.D;na();return Z}var b={a:Cb};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});pa??=f.locateFile?f.locateFile?f.locateFile("blosc_codec.wasm",y):y+"blosc_codec.wasm":(new URL("blosc_codec.wasm",import.meta.url)).href;return a((await sa(b)).instance)}());
(function(){function a(){f.calledRun=!0;if(!G){ma=!0;Z.z();da?.(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();va.push(b)}ua(va)}}if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)xa();ua(wa);f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()})();ma?moduleRtn=f:moduleRtn=new Promise((a,b)=>{da=a;ea=b});
;return moduleRtn}export default blosc_codec;
