async function blosc_codec(moduleArg={}){var moduleRtn;var b=moduleArg,t="./this.program",aa=import.meta.url,u="",v;try{u=(new URL(".",aa)).href}catch{}v=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var w=console.log.bind(console),z=console.error.bind(console),A,B=!1,C,D,E,F,G,H=!1;
function I(){var a=J.buffer;new Int8Array(a);new Int16Array(a);b.HEAPU8=F=new Uint8Array(a);new Uint16Array(a);b.HEAP32=new Int32Array(a);G=new Uint32Array(a);new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function L(a){b.onAbort?.(a);a="Aborted("+a+")";z(a);B=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");E?.(a);throw a;}var M;
async function ba(a){if(!A)try{var c=await v(a);return new Uint8Array(c)}catch{}if(a==M&&A)a=new Uint8Array(A);else throw"both async and sync fetching of the wasm failed";return a}async function da(a,c){try{var d=await ba(a);return await WebAssembly.instantiate(d,c)}catch(f){z(`failed to asynchronously prepare wasm: ${f}`),L(f)}}
async function ea(a){var c=M;if(!A)try{var d=fetch(c,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(d,a)}catch(f){z(`wasm streaming compile failed: ${f}`),z("falling back to ArrayBuffer instantiation")}return da(c,a)}class N{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var O=a=>{for(;0<a.length;)a.shift()(b)},P=[],Q=[],fa=()=>{var a=b.preRun.shift();Q.push(a)},R=!0,S=0,T={},U=a=>{if(!(a instanceof N||"unwind"==a))throw a;},V=a=>{C=a;R||0<S||(b.onExit?.(a),B=!0);throw new N(a);},ha=a=>{if(!B)try{a()}catch(c){U(c)}finally{if(!(R||0<S))try{C=a=C,V(a)}catch(c){U(c)}}},W={},Y=()=>{if(!X){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:t||"./this.program"},c;for(c in W)void 0===
W[c]?delete a[c]:a[c]=W[c];var d=[];for(c in a)d.push(`${c}=${a[c]}`);X=d}return X},X,ia=[null,[],[]],ja=globalThis.TextDecoder&&new TextDecoder;b.noExitRuntime&&(R=b.noExitRuntime);b.print&&(w=b.print);b.printErr&&(z=b.printErr);b.wasmBinary&&(A=b.wasmBinary);b.thisProgram&&(t=b.thisProgram);if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.shift()();
var ka,J,la={c:()=>L(""),b:()=>{R=!1;S=0},d:(a,c)=>{T[a]&&(clearTimeout(T[a].id),delete T[a]);if(!c)return 0;var d=setTimeout(()=>{delete T[a];ha(()=>ka(a,performance.now()))},c);T[a]={id:d,s:c};return 0},e:a=>{var c=F.length;a>>>=0;if(2147483648<a)return!1;for(var d=1;4>=d;d*=2){var f=c*(1+.2/d);f=Math.min(f,a+100663296);a:{f=(Math.min(2147483648,65536*Math.ceil(Math.max(a,f)/65536))-J.buffer.byteLength+65535)/65536|0;try{J.grow(f);I();var k=1;break a}catch(e){}k=void 0}if(k)return!0}return!1},g:(a,
c)=>{var d=0,f=0,k;for(k of Y()){var e=c+d;G[a+f>>2]=e;var n=k;for(var g=F,x=e,q=e+Infinity-1,h=0;h<n.length;++h){var l=n.codePointAt(h);if(127>=l){if(e>=q)break;g[e++]=l}else if(2047>=l){if(e+1>=q)break;g[e++]=192|l>>6;g[e++]=128|l&63}else if(65535>=l){if(e+2>=q)break;g[e++]=224|l>>12;g[e++]=128|l>>6&63;g[e++]=128|l&63}else{if(e+3>=q)break;g[e++]=240|l>>18;g[e++]=128|l>>12&63;g[e++]=128|l>>6&63;g[e++]=128|l&63;h++}}g[e]=0;n=e-x;d+=n+1;f+=4}return 0},h:(a,c)=>{var d=Y();G[a>>2]=d.length;a=0;for(var f of d){for(var k=
d=0;k<f.length;++k){var e=f.charCodeAt(k);127>=e?d++:2047>=e?d+=2:55296<=e&&57343>=e?(d+=4,++k):d+=3}a+=d+1}G[c>>2]=a;return 0},f:(a,c,d,f)=>{for(var k=0,e=0;e<d;e++){var n=G[c>>2],g=G[c+4>>2];c+=8;for(var x=0;x<g;x++){var q=a,h=F[n+x],l=ia[q];if(0===h||10===h){q=1===q?w:z;h=l;var r=0;var y=h;for(var p=r,m=p+void 0;y[p]&&!(p>=m);)++p;y=p;if(16<y-r&&h.buffer&&ja)h=ja.decode(h.subarray(r,y));else{for(p="";r<y;)if(m=h[r++],m&128){var K=h[r++]&63;if(192==(m&224))p+=String.fromCharCode((m&31)<<6|K);else{var ca=
h[r++]&63;m=224==(m&240)?(m&15)<<12|K<<6|ca:(m&7)<<18|K<<12|ca<<6|h[r++]&63;65536>m?p+=String.fromCharCode(m):(m-=65536,p+=String.fromCharCode(55296|m>>10,56320|m&1023))}}else p+=String.fromCharCode(m);h=p}q(h);l.length=0}else l.push(h)}k+=g}G[f>>2]=k;return 0},a:V},Z;
Z=await (async function(){function a(d){d=Z=d.exports;b._get_input_buf=d.k;b._free=d.l;b._do_compress=d.m;b._do_decompress=d.n;b._free_result=d.o;b._malloc=d.p;ka=d.q;J=d.i;I();return Z}var c={a:la};if(b.instantiateWasm)return new Promise(d=>{b.instantiateWasm(c,(f,k)=>{d(a(f,k))})});M??=b.locateFile?b.locateFile?b.locateFile("blosc_codec.wasm",u):u+"blosc_codec.wasm":(new URL("blosc_codec.wasm",import.meta.url)).href;return a((await ea(c)).instance)}());
(function(){function a(){b.calledRun=!0;if(!B){H=!0;Z.j();D?.(b);b.onRuntimeInitialized?.();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var c=b.postRun.shift();P.push(c)}O(P)}}if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)fa();O(Q);b.setStatus?(b.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>b.setStatus(""),1);a()},1)):a()})();var ma=0;function na(){ma||=b._malloc(4);return ma}
b.compress=function(a,c,d,f,k){var e=a instanceof Uint8Array?a:new Uint8Array(a.buffer?a.buffer:a,a.byteOffset||0,a.byteLength||a.length);a=e.length;var n=b._get_input_buf(a);if(!n)throw Error("Blosc: failed to allocate input buffer");b.HEAPU8.set(e,n);n=c.length;e=b._malloc(n+1);for(var g=0;g<n;g++)b.HEAPU8[e+g]=c.charCodeAt(g);b.HEAPU8[e+n]=0;c=na();d=b._do_compress(a,e,d,f,k,c);b._free(e);f=b.HEAP32[c>>2];if(!d||0>=f)throw Error("Blosc compression error: "+f);return new Uint8Array(b.HEAPU8.buffer,
d,f)};b.decompress=function(a){a=a instanceof Uint8Array?a:new Uint8Array(a.buffer?a.buffer:a,a.byteOffset||0,a.byteLength||a.length);var c=b._get_input_buf(a.length);if(!c)throw Error("Blosc: failed to allocate input buffer");b.HEAPU8.set(a,c);c=na();a=b._do_decompress(c);c=b.HEAP32[c>>2];if(!a||0>=c)throw Error("Blosc decompression error: "+c);return new Uint8Array(b.HEAPU8.buffer,a,c)};b.free_result=function(){b._free_result()};H?moduleRtn=b:moduleRtn=new Promise((a,c)=>{D=a;E=c});
;return moduleRtn}export default blosc_codec;
