async function blosc_codec(moduleArg={}){var moduleRtn;var b=moduleArg,t="./this.program",u=import.meta.url,v="",y;try{v=(new URL(".",u)).href}catch{}y=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var z=console.log.bind(console),A=console.error.bind(console),B,C=!1,D,E,G,H,I=!1;
function J(){var a=K.buffer;new Int8Array(a);new Int16Array(a);b.HEAPU8=G=new Uint8Array(a);new Uint16Array(a);b.HEAP32=new Int32Array(a);H=new Uint32Array(a);new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}var L;async function M(a){if(!B)try{var c=await y(a);return new Uint8Array(c)}catch{}if(a==L&&B)a=new Uint8Array(B);else throw"both async and sync fetching of the wasm failed";return a}
async function N(a,c){try{var d=await M(a);return await WebAssembly.instantiate(d,c)}catch(f){throw A(`failed to asynchronously prepare wasm: ${f}`),a=f,b.onAbort?.(a),a="Aborted("+a+")",A(a),C=!0,a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info."),E?.(a),a;}}
async function O(a){var c=L;if(!B)try{var d=fetch(c,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(d,a)}catch(f){A(`wasm streaming compile failed: ${f}`),A("falling back to ArrayBuffer instantiation")}return N(c,a)}
var P=a=>{for(;0<a.length;)a.shift()(b)},Q=[],R=[],aa=()=>{var a=b.preRun.shift();R.push(a)},S={},V=()=>{if(!U){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:t||"./this.program"},c;for(c in S)void 0===S[c]?delete a[c]:a[c]=S[c];var d=[];for(c in a)d.push(`${c}=${a[c]}`);U=d}return U},U,ba=[null,[],[]],W=globalThis.TextDecoder&&new TextDecoder;b.print&&(z=b.print);b.printErr&&(A=b.printErr);
b.wasmBinary&&(B=b.wasmBinary);b.thisProgram&&(t=b.thisProgram);if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.shift()();
var K,ca={b:a=>{var c=G.length;a>>>=0;if(2147483648<a)return!1;for(var d=1;4>=d;d*=2){var f=c*(1+.2/d);f=Math.min(f,a+100663296);a:{f=(Math.min(2147483648,65536*Math.ceil(Math.max(a,f)/65536))-K.buffer.byteLength+65535)/65536|0;try{K.grow(f);J();var k=1;break a}catch(e){}k=void 0}if(k)return!0}return!1},c:(a,c)=>{var d=0,f=0,k;for(k of V()){var e=c+d;H[a+f>>2]=e;var n=k;for(var g=G,w=e,q=e+Infinity-1,h=0;h<n.length;++h){var l=n.codePointAt(h);if(127>=l){if(e>=q)break;g[e++]=l}else if(2047>=l){if(e+
1>=q)break;g[e++]=192|l>>6;g[e++]=128|l&63}else if(65535>=l){if(e+2>=q)break;g[e++]=224|l>>12;g[e++]=128|l>>6&63;g[e++]=128|l&63}else{if(e+3>=q)break;g[e++]=240|l>>18;g[e++]=128|l>>12&63;g[e++]=128|l>>6&63;g[e++]=128|l&63;h++}}g[e]=0;n=e-w;d+=n+1;f+=4}return 0},d:(a,c)=>{var d=V();H[a>>2]=d.length;a=0;for(var f of d){for(var k=d=0;k<f.length;++k){var e=f.charCodeAt(k);127>=e?d++:2047>=e?d+=2:55296<=e&&57343>=e?(d+=4,++k):d+=3}a+=d+1}H[c>>2]=a;return 0},a:(a,c,d,f)=>{for(var k=0,e=0;e<d;e++){var n=
H[c>>2],g=H[c+4>>2];c+=8;for(var w=0;w<g;w++){var q=a,h=G[n+w],l=ba[q];if(0===h||10===h){q=1===q?z:A;h=l;var r=0;var x=h;for(var p=r,m=p+void 0;x[p]&&!(p>=m);)++p;x=p;if(16<x-r&&h.buffer&&W)h=W.decode(h.subarray(r,x));else{for(p="";r<x;)if(m=h[r++],m&128){var F=h[r++]&63;if(192==(m&224))p+=String.fromCharCode((m&31)<<6|F);else{var T=h[r++]&63;m=224==(m&240)?(m&15)<<12|F<<6|T:(m&7)<<18|F<<12|T<<6|h[r++]&63;65536>m?p+=String.fromCharCode(m):(m-=65536,p+=String.fromCharCode(55296|m>>10,56320|m&1023))}}else p+=
String.fromCharCode(m);h=p}q(h);l.length=0}else l.push(h)}k+=g}H[f>>2]=k;return 0}},X;
X=await (async function(){function a(d){d=X=d.exports;b._get_input_buf=d.g;b._free=d.h;b._do_compress=d.i;b._do_decompress=d.j;b._free_result=d.k;b._malloc=d.l;K=d.e;J();return X}var c={a:ca};if(b.instantiateWasm)return new Promise(d=>{b.instantiateWasm(c,(f,k)=>{d(a(f,k))})});L??=b.locateFile?b.locateFile?b.locateFile("blosc_codec.wasm",v):v+"blosc_codec.wasm":(new URL("blosc_codec.wasm",import.meta.url)).href;return a((await O(c)).instance)}());
(function(){function a(){b.calledRun=!0;if(!C){I=!0;X.f();D?.(b);b.onRuntimeInitialized?.();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var c=b.postRun.shift();Q.push(c)}P(Q)}}if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)aa();P(R);b.setStatus?(b.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>b.setStatus(""),1);a()},1)):a()})();var Y=0;function Z(){Y||=b._malloc(4);return Y}
b.compress=function(a,c,d,f,k){var e=a instanceof Uint8Array?a:new Uint8Array(a.buffer?a.buffer:a,a.byteOffset||0,a.byteLength||a.length);a=e.length;var n=b._get_input_buf(a);if(!n)throw Error("Blosc: failed to allocate input buffer");b.HEAPU8.set(e,n);n=c.length;e=b._malloc(n+1);for(var g=0;g<n;g++)b.HEAPU8[e+g]=c.charCodeAt(g);b.HEAPU8[e+n]=0;c=Z();d=b._do_compress(a,e,d,f,k,c);b._free(e);f=b.HEAP32[c>>2];if(!d||0>=f)throw Error("Blosc compression error: "+f);return new Uint8Array(b.HEAPU8.buffer,
d,f)};b.decompress=function(a){a=a instanceof Uint8Array?a:new Uint8Array(a.buffer?a.buffer:a,a.byteOffset||0,a.byteLength||a.length);var c=b._get_input_buf(a.length);if(!c)throw Error("Blosc: failed to allocate input buffer");b.HEAPU8.set(a,c);c=Z();a=b._do_decompress(c);c=b.HEAP32[c>>2];if(!a||0>=c)throw Error("Blosc decompression error: "+c);return new Uint8Array(b.HEAPU8.buffer,a,c)};b.free_result=function(){b._free_result()};I?moduleRtn=b:moduleRtn=new Promise((a,c)=>{D=a;E=c});
;return moduleRtn}export default blosc_codec;
