async function zstd_codec(moduleArg={}){var moduleRtn;var b=moduleArg,f=import.meta.url,g="",h;try{g=(new URL(".",f)).href}catch{}h=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var k=console.error.bind(console),l,m=!1,p,q,r,t,u=!1;
function v(){var a=w.buffer;new Int8Array(a);new Int16Array(a);b.HEAPU8=t=new Uint8Array(a);new Uint16Array(a);b.HEAP32=new Int32Array(a);new Uint32Array(a);new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function x(a){b.onAbort?.(a);a="Aborted("+a+")";k(a);m=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");r?.(a);throw a;}var y;
async function z(a){if(!l)try{var c=await h(a);return new Uint8Array(c)}catch{}if(a==y&&l)a=new Uint8Array(l);else throw"both async and sync fetching of the wasm failed";return a}async function A(a,c){try{var d=await z(a);return await WebAssembly.instantiate(d,c)}catch(e){k(`failed to asynchronously prepare wasm: ${e}`),x(e)}}
async function B(a){var c=y;if(!l)try{var d=fetch(c,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(d,a)}catch(e){k(`wasm streaming compile failed: ${e}`),k("falling back to ArrayBuffer instantiation")}return A(c,a)}class C{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var D=a=>{for(;0<a.length;)a.shift()(b)},E=[],F=[],G=()=>{var a=b.preRun.shift();F.push(a)},H=!0,I=0,J={},K=a=>{if(!(a instanceof C||"unwind"==a))throw a;},L=a=>{p=a;H||0<I||(b.onExit?.(a),m=!0);throw new C(a);},M=a=>{if(!m)try{a()}catch(c){K(c)}finally{if(!(H||0<I))try{p=a=p,L(a)}catch(c){K(c)}}};b.noExitRuntime&&(H=b.noExitRuntime);b.printErr&&(k=b.printErr);b.wasmBinary&&(l=b.wasmBinary);if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.shift()();
var N,w,O={c:()=>x(""),b:()=>{H=!1;I=0},d:(a,c)=>{J[a]&&(clearTimeout(J[a].id),delete J[a]);if(!c)return 0;var d=setTimeout(()=>{delete J[a];M(()=>N(a,performance.now()))},c);J[a]={id:d,s:c};return 0},e:a=>{var c=t.length;a>>>=0;if(2147483648<a)return!1;for(var d=1;4>=d;d*=2){var e=c*(1+.2/d);e=Math.min(e,a+100663296);a:{e=(Math.min(2147483648,65536*Math.ceil(Math.max(a,e)/65536))-w.buffer.byteLength+65535)/65536|0;try{w.grow(e);v();var n=1;break a}catch(T){}n=void 0}if(n)return!0}return!1},a:L},
P;P=await (async function(){function a(d){d=P=d.exports;b._get_input_buf=d.h;b._free=d.i;b._malloc=d.j;b._get_error_msg=d.k;b._do_compress=d.l;b._do_decompress=d.m;b._free_result=d.n;N=d.o;w=d.f;v();return P}var c={a:O};if(b.instantiateWasm)return new Promise(d=>{b.instantiateWasm(c,(e,n)=>{d(a(e,n))})});y??=b.locateFile?b.locateFile?b.locateFile("zstd_codec.wasm",g):g+"zstd_codec.wasm":(new URL("zstd_codec.wasm",import.meta.url)).href;return a((await B(c)).instance)}());
(function(){function a(){b.calledRun=!0;if(!m){u=!0;P.g();q?.(b);b.onRuntimeInitialized?.();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var c=b.postRun.shift();E.push(c)}D(E)}}if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)G();D(F);b.setStatus?(b.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>b.setStatus(""),1);a()},1)):a()})();var Q=0;function R(){Q||=b._malloc(4);return Q}
function S(){var a=b._get_error_msg();if(!a)return"zstd: unknown error";for(var c="",d=0;;d++){var e=b.HEAPU8[a+d];if(0===e)break;c+=String.fromCharCode(e)}return c||"zstd: unknown error"}
b.compress=function(a,c){var d=a instanceof Uint8Array?a:new Uint8Array(a.buffer?a.buffer:a,a.byteOffset||0,a.byteLength||a.length);a=d.length;var e=b._get_input_buf(a);if(!e)throw Error("Zstd: failed to allocate input buffer");b.HEAPU8.set(d,e);d=R();c=b._do_compress(a,c,d);a=b.HEAP32[d>>2];if(!c||0>=a)throw Error(S());return new Uint8Array(b.HEAPU8.buffer,c,a)};
b.decompress=function(a){var c=a instanceof Uint8Array?a:new Uint8Array(a.buffer?a.buffer:a,a.byteOffset||0,a.byteLength||a.length);a=c.length;var d=b._get_input_buf(a);if(!d)throw Error("Zstd: failed to allocate input buffer");b.HEAPU8.set(c,d);c=R();a=b._do_decompress(a,c);c=b.HEAP32[c>>2];if(!a||0>c)throw Error(S());return new Uint8Array(b.HEAPU8.buffer,a,c)};b.free_result=function(){b._free_result()};u?moduleRtn=b:moduleRtn=new Promise((a,c)=>{q=a;r=c});
;return moduleRtn}export default zstd_codec;
